on:
  pull_request:
    branches: main
    types: [edited]

name: deps-rerun

jobs:
  rerun:
    uses: cynkra/blockr.ci/.github/workflows/deps-rerun.yaml@17-pr-gates
    secrets:
      BLOCKR_PAT: ${{ secrets.BLOCKR_PAT }}
